apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-website-deployment
spec:
  template:
    metadata:
      name: news-website
      labels:
        app: news-website
    spec:
      containers:
        - name: news-website-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: news-website-configmap
  replicas: 3
  selector:
    matchLabels:
      app: news-website
  
